# Generated by Django 6.0.1 on 2026-01-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='price_cents',
            field=models.IntegerField(default=0),
        ),
    ]
